name: Open be-fe pull requests

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  open-befe-prs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}
        exclude:
          - label: major
          - label: minor
          - label: patch

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get last commit message
        run: |
          commitmsg=$(git log --format=%B -n 1 ${{ github.event.after }}) | tr \" \\\"
          echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV

      - name: Create feature branch and PR in be-fe repos
        if: ${{ startsWith(matrix.label, 'be-fe-') }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: rohnjeynolds/${{ matrix.label }}
          event-type: elementish-pr-opened
          client-payload: '{
            "actor": "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>",
            "feature-branch": "${{ github.head_ref }}",
            "commit-message": "${{ env.COMMIT_MESSAGE }}"
          }'
