name: Update version

on:
  push:
    branches:
      - main

jobs:
  update-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Determines next minor version
      - name: Get next version
        id: semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
          tag_format: "v%major%.%minor%.%patch%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ steps.semver.outputs }}
          echo ${{ steps.semver.outputs.tag }}

      # Runs a set of commands using the runners shell
      - name: Update package.json
        run: |
          echo ${{ steps.semver.outputs }}
          echo ${{ steps.semver.outputs.tag }}
          version=${${{ steps.semver.outputs.tag }}:1}
          echo $version
          # sed "s#.*\"version\".*#  \"version\": \"$version\",#" package.json
          # git add package.json
          # git commit -m "Updating version to $version"
          # git tag -a ${} steps.semver.outputs.tag }}
          # git push
          # git push --tags
