name: Open be-fe pull request

on:
  pull_request:
    types:
      - synchronize
    branches:
      - main

jobs:
  update-brand-sites:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        label: ${{ github.event.pull_request.labels.*.name }}
        exclude:
          - label: major
          - label: minor
          - label: patch

    steps:
      - name: Set node version
        if: ${{ startsWith(matrix.label, 'be-fe-') }}
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.3"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Get last commit message
        run: echo "commit-message=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV

      - name: Update feature branch in be-fe repos
        if: ${{ startsWith(matrix.label, 'be-fe-') }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: rohnjeynolds/${{ matrix.label }}
          event-type: element-feature-branch-updated
          client-payload: '{
            "actor": "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>",
            "feature-branch": "${{ github.head_ref }}",
            "commit-message": "${{ env.commit-message }}"
          }'
