name: Update version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  update-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Determines next minor version
      - name: Get next version
        id: semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Updates package.json and package-lock.json with new version.
      - name: Update package.json
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Github Actions"
          tag=${{steps.semver.outputs.tag}}
          version="${tag:1}"
          npm version $version
          git status
          git push --tags
