name: Update version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  update-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      # Determines next minor version
      - name: Get next version
        id: semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Update package.json
        run: |
          tag=${{steps.semver.outputs.tag}}
          version="${tag:1}"
          sed -i "s/.*\"version\".*/  \"version\": \"$version\",/" package.json
          git add package.json
          npm i --package-lock-only
          git commit -m "Updating version in package.json to $version."
          git tag -a $tag
          git push
          git push --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
