name: Update version

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  update-version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '12.16.3'

      # Determines next minor version
      - name: Get next version
        id: semver
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
          release_strategy: none
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set new version in environment variable'
        run: |
          tag=${{steps.semver.outputs.tag}}
          version="${tag:1}"
          echo "tag=$tag" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV

      - name: 'Update package.json version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ env.version }}
          git-tag-version: true

      # Updates package.json and package-lock.json.
      #- name: Update package.json
      #  run: |
      #    npm --version
      #    tag=${{steps.semver.outputs.tag}}
      #    version="${tag:1}"
      #    sed -i "s/.*\"version\".*/  \"version\": \"$version\",/" package.json
      #    git add package.json
      #    npm i --package-lock-only
      #    git commit -m "Updating version in package.json to $version."
      #    git tag -a $tag
      #    git push
      #    git push --tags
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Commit and push package.json and package-lock.json changes.
      #- name: Commit package file changes
      #  uses: github-actions-x/commit@v2.8
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    push-branch: 'main'
      #    commit-message: 'Update package.json and package-lock.json with new version.'
      #    force-add: 'true'
      #    files: a.txt b.txt c.txt dirA/ dirB/ dirC/a.txt
      #    name: commiter name
      #    email: my.github@email.com 
